[#101] Newest publication list on landing page should only contain it…
ThULB/ThUniBib pull request #102
Opened 2022-06-07 11:35 UTC by Possommi

…ems being part of the statistics

2022-06-07 11:41 UTC, Possommi commented
requires https://mycore.atlassian.net/browse/UBO-165 to be merged

2022-06-10 08:14 UTC, kkrebs commented on common/src/main/resources/config/thunibib-common/messages_en.properties
> +facets.facet.origin                             = Structural unit of the university
only facets.facet.origin_exact needed here

2022-06-10 08:16 UTC, kkrebs commented on jena/src/main/resources/META-INF/resources/index.xed
> +  <xinclude uri="xslStyle:response-newest:solr:q=%2BpartOf:true+status:confirmed+AND+year:NOW&amp;rows=4&amp;sort=year+desc,created+desc&amp;facet=false&amp;fl=id,year"/>
should be:
xslStyle:response-newest:solr:q=partOf:true+AND+status:confirmed+AND+year:NOW&amp;rows=4&amp;sort=year+desc,created+desc&amp;facet=false&amp;fl=id,year

2022-06-10 08:16 UTC, kkrebs requested changes
see comments

2022-06-13 07:15 UTC, merged